### ISSUE TITLE
step: 3-normalize_urls, link-analyzer, Summary: Hi Lane, I think the

### ISSUE THREAD

**Issue by wagslane** [bootdotdev/projects#25]
Comment: Hi Lane, I think there is a typo with added "s" in "modules.exports" it should be "module.exports".

From: tsohlove@gmail.com

**Comment by ts-oh** [comment]
Hi Lane, I'm a bootdev member would it be ok for me to create a pull request on this to fix it?

**Comment by wagslane** [comment]
@ts-oh for sure!
