### ISSUE TITLE
step: 5-main, link-analyzer, Summary: Link for the node JS

### ISSUE THREAD

**Issue by wagslane** [bootdotdev/projects#27]
Comment: Link for the node JS docs is 404. 

I believe the link has either been updated or moved here: https://nodejs.dev/en/learn/accept-input-from-the-command-line-in-nodejs/

From: code@petros.io

**Comment by ts-oh** [comment]
Looks like #28 and #29 is a duplicate issue. But I'm wondering which one is the correct updated link? 

https://nodejs.org/en/knowledge/command-line/how-to-parse-command-line-arguments/
**or**
https://nodejs.dev/en/learn/accept-input-from-the-command-line-in-nodejs/
