### ISSUE TITLE
step: 5-main, link-analyzer, Summary: Command Line Argumen

### ISSUE THREAD

**Issue by wagslane** [bootdotdev/projects#29]
Comment: Command Line Argument link returns page not found.
https://nodejs.dev/en/learn/nodejs-accept-arguments-from-the-command-line

From: tsohlove@gmail.com

**Comment by DEEJAY29** [comment]
https://nodejs.org/en/knowledge/command-line/how-to-parse-command-line-arguments/
This can be added instead,
its a valid link

**Comment by DEEJAY29** [comment]
https://nodejs.org/en/knowledge/command-line/how-to-parse-command-line-arguments/
This can be added instead,
its a valid link

You can assign me if you want

**Comment by ALires** [comment]
Updated
